Repository florimondmanca/uptv, pull requests merged in 2018-10, with the labels that each got.

#1 Add TravisCI configuration
  .travis.yml
  README.md
Labels: enhancement

#2 Add Heroku deployment
  .gitignore
  Procfile
  requirements.txt
  uptv/settings-production.py
  uptv/settings.py
  uptv/wsgi.py
Labels: enhancement

#5 Add custom user model
  requirements.txt
  uptv/settings.py
  users/__init__.py
  users/admin.py
  users/apps.py
  users/migrations/0001_initial.py
  users/migrations/__init__.py
  users/models.py
Labels: enhancement

#3 Add barebones search form view
  README.md
  series/forms.py
  series/templates/series/search_series.html
  series/urls.py
  series/views.py
  uptv/settings.py
  uptv/urls.py
Labels: enhancement

#9 Add backend models for the favorites system
  series/admin.py
  series/migrations/0001_initial.py
  series/migrations/0002_auto_20181016_1216.py
  series/migrations/0003_apishow_followers.py
  series/migrations/0004_apishow_first_followed.py
  series/models.py
Labels: enhancement

#12 Show details page
  series/static/__init__.py
  series/static/series/__init__.py
  series/static/series/search_results.css
  series/static/series/show_details.css
  series/static/series/style.css
  series/static/series/uptv_logo.png
  series/templates/series/search_results.html
  series/templates/series/search_series.html
  series/templates/series/show_details.html
  series/urls.py
  series/views.py
Labels: enhancement

#13 Refactor TMDB API functions
  series/APILibrary.py
  series/views.py
  tmdb/__init__.py
  tmdb/apps.py
  tmdb/client.py
  tmdb/datatypes.py
  tmdb/parsers/__init__.py
  tmdb/parsers/base.py
  tmdb/parsers/shows.py
  tmdb/shortcuts.py
  uptv/settings.py
Labels: refactor

#19 Serve static files in production using WhiteNoise
  requirements.txt
  uptv/settings.py
Labels: bug, enhancement

#18 Add SendGrid email configuration
  README.md
  requirements.txt
  uptv/settings.py
Labels: enhancement

#17 Specify TMDB_API_KEY in settings.py
  tmdb/client.py
  tmdb/settings.py
  uptv/settings.py
Labels: refactor

#15 Add alerts worker
  alerts/__init__.py
  alerts/apps.py
  alerts/jobs.py
  alerts/settings.py
  alerts/worker.py
  tmdb/client.py
  tmdb/pagination.py
  uptv/settings.py
Labels: enhancement

#27 Add season cards
  series/static/series/search_results.css
  series/static/series/show_details.css
  series/templates/series/show_details.html
  series/views.py
  static/base.css
  tmdb/client.py
  tmdb/datatypes.py
  tmdb/parsers/episodes.py
  tmdb/parsers/mixins.py
  tmdb/parsers/seasons.py
  tmdb/parsers/shows.py
  tmdb/shortcuts.py
Labels: enhancement

#28 Containerize app
  Dockerfile
  Procfile
  README.md
  docker-compose.yml
  docker-entrypoint.sh
  uptv/settings.py
Labels: enhancement

#31 Improve and add tests for subscribe/unsubscribe API endpoints
  series/views.py
  tests/test_series/__init__.py
  tests/test_series/test_subscribe.py
Labels: enhancement, refactor, testing

#29 Add tests for signing up a new user
  tests/test_users/__init__.py
  tests/test_users/test_signup.py
Labels: enhancement, testing

#32 Account buttons
  templates/base.html
  users/templates/users/login.html
  users/templates/users/signup.html
Labels: enhancement
